### ISSUE TITLE
[BUG] Segmentation fault with own dictonary

### ISSUE THREAD

**Issue by raskhadafi** [evan/raspell#4] opened 2011-12-05 10:15 UTC
Hi 
I get an error with following output:

```
/Users/roman/dev/ruby/cyt/katalog/app/controllers/dossiers_controller.rb:189: [BUG] Segmentation fault
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-darwin10.8.0]

Abort trap: 6
```

Here is the source code:
https://github.com/CyTeam/katalog/blob/master/app/controllers/dossiers_controller.rb#L189

``` ruby
word = "32.3"
spell_checker = Aspell.new1({"dict-dir" => Rails.root.join('db', 'aspell').to_s, "lang"=>"kt", "encoding"=>"UTF-8"})
spell_checker.set_option("ignore-case", "true")
spell_checker.suggestion_mode = Aspell::NORMAL
suggestion = spell_checker.suggest(word).first
```

I also tried the same directly in the aspell interactive console and there was the return nothing.

Do you have any idea what may caus the segmentation fault?
greez
Roman

**Comment by evan** [comment] 2011-12-06 06:52
I can't reproduce, on 1.8.7 or 1.9.3.

```
ruby-1.9.3-p0 :010 > s = Aspell.new1("encoding"=>"UTF-8")
 => #<Aspell:0x007f8a92882df8> 
ruby-1.9.3-p0 :011 > s.set_option("ignore-case", "true")
 => #<Aspell:0x007f8a92882df8> 
ruby-1.9.3-p0 :012 > s.suggestion_mode= Aspell::NORMAL 
 => "normal" 
ruby-1.9.3-p0 :013 > s.suggest("32.3").first
 => "W" 
```

Can you submit a pull request with a failing test?

**Comment by raskhadafi** [comment] 2011-12-13 08:03
May this could be helpful. I ran the rails application with the GNU debugger and I received following output:

```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000500000025
0x0000000101a4f738 in aspeller::AffixMgr::suffix_check ()

```

**Comment by evan** [comment] 2011-12-13 08:05
No, not helpful, sorry. I really need you to isolate a reproducible case.

**Comment by huerlisi** [comment] 2011-12-13 10:05
Working on isolating but it's damn hard.

It sometimes does segfault on a very simple test case, other times it doesn't:

```
shuerlimann@okh:~/src/katalog$ rails c
Sass::Compiler#on_updating_stylesheet callback is deprecated and will be removed in a future release. Use Sass::Compiler#on_updated_stylesheet instead, which is run after stylesheet compilation.
Loading development environment (Rails 3.0.11)
irb(main):001:0> spell_checker = Aspell.new1({"dict-dir" => Rails.root.join('db', 'aspell').to_s, "lang"=>"kt", "encoding"=>"UTF-8"})
=> #<Aspell:0xb6760f64>
irb(main):002:0> spell_checker.suggest('32.2').first
=> "A"
irb(main):003:0> spell_checker.suggest('32.2').first
=> "A"
irb(main):004:0> shuerlimann@okh:~/src/katalog$ rails c
Sass::Compiler#on_updating_stylesheet callback is deprecated and will be removed in a future release. Use Sass::Compiler#on_updated_stylesheet instead, which is run after stylesheet compilation.
Loading development environment (Rails 3.0.11)
irb(main):001:0> spell_checker = Aspell.new1({"dict-dir" => Rails.root.join('db', 'aspell').to_s, "lang"=>"kt", "encoding"=>"UTF-8"})
=> #<Aspell:0xb664dc08>
irb(main):002:0> spell_checker.suggest('32.2').first
(irb):2: [BUG] Segmentation fault
ruby 1.8.7 (2010-08-16 patchlevel 302) [i686-linux]

Aborted
```

What I've found 'till now:

Installing/Compiling:
1. It does segfault almost every time in the above test case when raspell was installed using rubygems 1.3.7
2. It does segfault seldom if raspell is installed using rubygems 1.8.10
3. Haven't got it segfault when using irb, not rails console
4. Haven't got it segfault when using local checkout of raspell compiled locally

Calling order
1. It does segfault when doing the above testcase
2. Haven't got it segfault if I add a simple 's = Aspell.new' before doing the 'Aspell.new1' call

Argument
1. It does segfault when called with a number including points
2. Haven't got it segfault when called using string

Dictionary
1. It does segfault with our custom dictionary
2. Haven't got i segfaulting when using en_US dictionary

I'm out of ideas:-(

I understand that you can't reproduce and am willing to do what I can to do so. But I don't know how to get more information. Do you know any debugging technique I could use to give you more information?

**Comment by evan** [comment] 2011-12-13 10:06
Try grabbing the C backtrace from GDB (type 'bt' at the prompt).

**Comment by raskhadafi** [comment] 2011-12-13 10:36
So here is the C backtrace from GDB

```
#0  0x0000000101a4f74c in aspeller::AffixMgr::suffix_check ()
#1  0x0000000101a505c3 in aspeller::AffixMgr::affix_check ()
#2  0x0000000101a2c6ee in (anonymous namespace)::Working::try_word ()
#3  0x0000000101a2c8cf in (anonymous namespace)::Working::try_one_edit_word ()
#4  0x0000000101a29a50 in (anonymous namespace)::SuggestImpl::suggest ()
#5  0x0000000101a3c29e in aspeller::SpellerImpl::suggest ()
#6  0x0000000101a62d26 in aspell_speller_suggest ()
#7  0x00000001007ce5d8 in aspell_suggest ()
#8  0x000000010002e9cb in call_cfunc ()
#9  0x000000010002dbb8 in rb_call0 ()
#10 0x000000010002f49e in rb_call ()
#11 0x00000001000267f8 in rb_eval ()
#12 0x000000010002654a in rb_eval ()
#13 0x0000000100027b84 in rb_eval ()
#14 0x000000010002b2d4 in rb_yield_0 ()
#15 0x000000010002b70b in rb_yield ()
#16 0x00000001000af795 in str_gsub ()
#17 0x00000001000afeaa in rb_str_gsub ()
#18 0x000000010002e994 in call_cfunc ()
#19 0x000000010002dbb8 in rb_call0 ()
#20 0x000000010002f49e in rb_call ()
#21 0x00000001000267f8 in rb_eval ()
#22 0x000000010002546c in rb_eval ()
#23 0x000000010002e530 in rb_call0 ()
#24 0x000000010002f49e in rb_call ()
#25 0x0000000100026b80 in rb_eval ()
#26 0x000000010002e530 in rb_call0 ()
#27 0x000000010002f49e in rb_call ()
#28 0x000000010002f65c in rb_f_send ()
#29 0x000000010002e994 in call_cfunc ()
#30 0x000000010002dbb8 in rb_call0 ()
#31 0x000000010002f49e in rb_call ()
#32 0x000000010002fc77 in rb_call_super ()
#33 0x0000000100026fd2 in rb_eval ()
#34 0x0000000100027afb in rb_eval ()
#35 0x000000010002e530 in rb_call0 ()
#36 0x000000010002f49e in rb_call ()
#37 0x0000000100026b2f in rb_eval ()
#38 0x000000010002e530 in rb_call0 ()
#39 0x000000010002f49e in rb_call ()
#40 0x000000010002fc77 in rb_call_super ()
#41 0x0000000100026fd2 in rb_eval ()
#42 0x000000010002e530 in rb_call0 ()
#43 0x000000010002f49e in rb_call ()
#44 0x000000010002fc77 in rb_call_super ()
#45 0x0000000100026fd2 in rb_eval ()
#46 0x000000010002b2d4 in rb_yield_0 ()
#47 0x00000001000258e8 in rb_eval ()
#48 0x0000000100027afb in rb_eval ()
#49 0x000000010002e530 in rb_call0 ()
#50 0x000000010002f49e in rb_call ()
#51 0x000000010002f65c in rb_f_send ()
#52 0x000000010002e994 in call_cfunc ()
#53 0x000000010002dbb8 in rb_call0 ()
#54 0x000000010002f49e in rb_call ()
#55 0x0000000100026b2f in rb_eval ()
#56 0x0000000100036008 in block_pass ()
#57 0x00000001000251c8 in rb_eval ()
#58 0x000000010002e530 in rb_call0 ()
#59 0x000000010002f49e in rb_call ()
#60 0x000000010002f65c in rb_f_send ()
#61 0x000000010002e994 in call_cfunc ()
#62 0x000000010002dbb8 in rb_call0 ()
#63 0x000000010002f49e in rb_call ()
#64 0x0000000100026b2f in rb_eval ()
#65 0x0000000100036008 in block_pass ()
#66 0x00000001000251c8 in rb_eval ()
#67 0x000000010002e530 in rb_call0 ()
#68 0x000000010002f49e in rb_call ()
#69 0x0000000100026b2f in rb_eval ()
#70 0x000000010002546c in rb_eval ()
#71 0x000000010002e530 in rb_call0 ()
#72 0x000000010002f49e in rb_call ()
#73 0x000000010002fc77 in rb_call_super ()
#74 0x0000000100026fd2 in rb_eval ()
#75 0x00000001000259ac in rb_eval ()
#76 0x000000010002e530 in rb_call0 ()
#77 0x000000010002f49e in rb_call ()
#78 0x000000010002fc77 in rb_call_super ()
#79 0x0000000100026fd2 in rb_eval ()
#80 0x0000000100027b84 in rb_eval ()
#81 0x000000010002b2d4 in rb_yield_0 ()
#82 0x00000001000258e8 in rb_eval ()
#83 0x000000010002b2d4 in rb_yield_0 ()
#84 0x00000001000258e8 in rb_eval ()
#85 0x00000001000259ac in rb_eval ()
#86 0x0000000100025c04 in rb_eval ()
#87 0x000000010002e530 in rb_call0 ()
#88 0x000000010002f49e in rb_call ()
#89 0x00000001000267f8 in rb_eval ()
#90 0x000000010002546c in rb_eval ()
#91 0x000000010002e530 in rb_call0 ()
#92 0x000000010002f49e in rb_call ()
#93 0x00000001000267f8 in rb_eval ()
#94 0x000000010002546c in rb_eval ()
#95 0x000000010002e530 in rb_call0 ()
#96 0x000000010002f49e in rb_call ()
#97 0x0000000100026b2f in rb_eval ()
#98 0x0000000100027afb in rb_eval ()
#99 0x000000010002e530 in rb_call0 ()
#100 0x000000010002f49e in rb_call ()
#101 0x0000000100026b2f in rb_eval ()
#102 0x000000010002e530 in rb_call0 ()
#103 0x000000010002f49e in rb_call ()
#104 0x000000010002fc77 in rb_call_super ()
#105 0x0000000100026fd2 in rb_eval ()
#106 0x0000000100025c04 in rb_eval ()
#107 0x000000010002e530 in rb_call0 ()
#108 0x000000010002f49e in rb_call ()
#109 0x0000000100026b2f in rb_eval ()
#110 0x000000010002e530 in rb_call0 ()
#111 0x000000010002f49e in rb_call ()
#112 0x0000000100026b2f in rb_eval ()
#113 0x000000010002e530 in rb_call0 ()
#114 0x000000010002f49e in rb_call ()
#115 0x000000010002fc77 in rb_call_super ()
#116 0x0000000100026fd2 in rb_eval ()
#117 0x000000010002e530 in rb_call0 ()
#118 0x000000010002f49e in rb_call ()
#119 0x00000001000267f8 in rb_eval ()
#120 0x000000010002b2d4 in rb_yield_0 ()
#121 0x000000010003565f in proc_invoke ()
#122 0x0000000100035817 in rb_proc_call ()
#123 0x000000010002e975 in call_cfunc ()
#124 0x000000010002dbb8 in rb_call0 ()
#125 0x000000010002f49e in rb_call ()
#126 0x00000001000267f8 in rb_eval ()
#127 0x000000010002e530 in rb_call0 ()
#128 0x000000010002f49e in rb_call ()
#129 0x0000000100026b2f in rb_eval ()
#130 0x000000010002e530 in rb_call0 ()
#131 0x000000010002f49e in rb_call ()
#132 0x00000001000267f8 in rb_eval ()
#133 0x0000000100027b84 in rb_eval ()
#134 0x000000010002b2d4 in rb_yield_0 ()
#135 0x00000001000258e8 in rb_eval ()
#136 0x000000010002b2d4 in rb_yield_0 ()
#137 0x00000001000258e8 in rb_eval ()
#138 0x000000010002e530 in rb_call0 ()
#139 0x000000010002f49e in rb_call ()
#140 0x00000001000267f8 in rb_eval ()
#141 0x000000010002546c in rb_eval ()
#142 0x000000010002e530 in rb_call0 ()
#143 0x000000010002f49e in rb_call ()
#144 0x0000000100026b2f in rb_eval ()
#145 0x000000010002546c in rb_eval ()
#146 0x000000010002e530 in rb_call0 ()
#147 0x000000010002f49e in rb_call ()
#148 0x00000001000267f8 in rb_eval ()
#149 0x000000010002e530 in rb_call0 ()
#150 0x000000010002f49e in rb_call ()
#151 0x00000001000267f8 in rb_eval ()
#152 0x0000000100027afb in rb_eval ()
#153 0x00000001000259ac in rb_eval ()
#154 0x000000010002e530 in rb_call0 ()
#155 0x000000010002f49e in rb_call ()
#156 0x00000001000267f8 in rb_eval ()
#157 0x000000010002e530 in rb_call0 ()
#158 0x000000010002f49e in rb_call ()
#159 0x00000001000267f8 in rb_eval ()
#160 0x000000010002b2d4 in rb_yield_0 ()
#161 0x000000010003e728 in rb_f_catch ()
#162 0x000000010002e9cb in call_cfunc ()
#163 0x000000010002dbb8 in rb_call0 ()
#164 0x000000010002f49e in rb_call ()
#165 0x0000000100026b2f in rb_eval ()
#166 0x000000010002546c in rb_eval ()
#167 0x0000000100027afb in rb_eval ()
#168 0x000000010002e530 in rb_call0 ()
#169 0x000000010002f49e in rb_call ()
#170 0x00000001000267f8 in rb_eval ()
#171 0x0000000100025816 in rb_eval ()
#172 0x0000000100027a9c in rb_eval ()
#173 0x000000010002e530 in rb_call0 ()
#174 0x000000010002f49e in rb_call ()
#175 0x00000001000267f8 in rb_eval ()
#176 0x000000010002e530 in rb_call0 ()
#177 0x000000010002f49e in rb_call ()
#178 0x00000001000267f8 in rb_eval ()
#179 0x000000010002e530 in rb_call0 ()
#180 0x000000010002f49e in rb_call ()
#181 0x00000001000267f8 in rb_eval ()
#182 0x000000010002e530 in rb_call0 ()
#183 0x000000010002f49e in rb_call ()
#184 0x00000001000267f8 in rb_eval ()
#185 0x0000000100025c04 in rb_eval ()
#186 0x000000010002e530 in rb_call0 ()
#187 0x000000010002f49e in rb_call ()
#188 0x00000001000267f8 in rb_eval ()
#189 0x0000000100027afb in rb_eval ()
#190 0x000000010002e530 in rb_call0 ()
#191 0x000000010002f49e in rb_call ()
#192 0x00000001000267f8 in rb_eval ()
#193 0x0000000100025816 in rb_eval ()
#194 0x0000000100027a9c in rb_eval ()
#195 0x000000010002e530 in rb_call0 ()
#196 0x000000010002f49e in rb_call ()
#197 0x00000001000267f8 in rb_eval ()
#198 0x000000010002b2d4 in rb_yield_0 ()
#199 0x00000001000258e8 in rb_eval ()
#200 0x0000000100025c04 in rb_eval ()
#201 0x000000010002e530 in rb_call0 ()
#202 0x000000010002f49e in rb_call ()
#203 0x00000001000267f8 in rb_eval ()
#204 0x0000000100036008 in block_pass ()
#205 0x00000001000251c8 in rb_eval ()
#206 0x000000010002e530 in rb_call0 ()
#207 0x000000010002f49e in rb_call ()
#208 0x00000001000267f8 in rb_eval ()
#209 0x000000010002546c in rb_eval ()
#210 0x000000010002e530 in rb_call0 ()
#211 0x000000010002f49e in rb_call ()
#212 0x00000001000267f8 in rb_eval ()
#213 0x0000000100025c04 in rb_eval ()
#214 0x000000010002e530 in rb_call0 ()
#215 0x000000010002f49e in rb_call ()
#216 0x00000001000267f8 in rb_eval ()
#217 0x000000010002b2d4 in rb_yield_0 ()
#218 0x00000001000258e8 in rb_eval ()
#219 0x0000000100027afb in rb_eval ()
#220 0x00000001000259ac in rb_eval ()
#221 0x000000010002e530 in rb_call0 ()
#222 0x000000010002f49e in rb_call ()
#223 0x0000000100026b2f in rb_eval ()
#224 0x000000010002546c in rb_eval ()
#225 0x000000010002e530 in rb_call0 ()
#226 0x000000010002f49e in rb_call ()
#227 0x00000001000267f8 in rb_eval ()
#228 0x0000000100025816 in rb_eval ()
#229 0x0000000100027a9c in rb_eval ()
#230 0x000000010002e530 in rb_call0 ()
#231 0x000000010002f49e in rb_call ()
#232 0x00000001000267f8 in rb_eval ()
#233 0x000000010002e530 in rb_call0 ()
#234 0x000000010002f49e in rb_call ()
#235 0x00000001000267f8 in rb_eval ()
#236 0x0000000100025816 in rb_eval ()
#237 0x0000000100027a9c in rb_eval ()
#238 0x00000001000259ac in rb_eval ()
#239 0x000000010002e530 in rb_call0 ()
#240 0x000000010002f49e in rb_call ()
#241 0x00000001000267f8 in rb_eval ()
#242 0x0000000100025c04 in rb_eval ()
#243 0x000000010002e530 in rb_call0 ()
#244 0x000000010002f49e in rb_call ()
#245 0x00000001000267f8 in rb_eval ()
#246 0x0000000100025816 in rb_eval ()
#247 0x0000000100027a9c in rb_eval ()
#248 0x000000010002e530 in rb_call0 ()
#249 0x000000010002f49e in rb_call ()
#250 0x00000001000267f8 in rb_eval ()
#251 0x0000000100025c04 in rb_eval ()
#252 0x000000010002e530 in rb_call0 ()
#253 0x000000010002f49e in rb_call ()
#254 0x00000001000267f8 in rb_eval ()
#255 0x000000010002b2d4 in rb_yield_0 ()
#256 0x000000010002b70b in rb_yield ()
#257 0x000000010002cc87 in rb_ensure ()
#258 0x000000010079cbeb in rb_mutex_synchronize ()
#259 0x000000010002e9ac in call_cfunc ()
#260 0x000000010002dbb8 in rb_call0 ()
#261 0x000000010002f49e in rb_call ()
#262 0x00000001000267f8 in rb_eval ()
#263 0x000000010002546c in rb_eval ()
#264 0x0000000100025c04 in rb_eval ()
#265 0x000000010002e530 in rb_call0 ()
#266 0x000000010002f49e in rb_call ()
#267 0x00000001000267f8 in rb_eval ()
#268 0x000000010002e530 in rb_call0 ()
#269 0x000000010002f49e in rb_call ()
#270 0x00000001000267f8 in rb_eval ()
#271 0x0000000100025816 in rb_eval ()
#272 0x0000000100027a9c in rb_eval ()
#273 0x000000010002e530 in rb_call0 ()
#274 0x000000010002f49e in rb_call ()
#275 0x00000001000267f8 in rb_eval ()
#276 0x000000010002e530 in rb_call0 ()
#277 0x000000010002f49e in rb_call ()
#278 0x000000010002f65c in rb_f_send ()
#279 0x000000010002e994 in call_cfunc ()
#280 0x000000010002dbb8 in rb_call0 ()
#281 0x000000010002f49e in rb_call ()
#282 0x00000001000267f8 in rb_eval ()
#283 0x0000000100035ebc in block_pass ()
#284 0x00000001000251c8 in rb_eval ()
#285 0x000000010002e530 in rb_call0 ()
#286 0x000000010002f49e in rb_call ()
#287 0x000000010002fb29 in rb_funcall2 ()
#288 0x000000010002d4fd in method_missing ()
#289 0x000000010002f386 in rb_call ()
#290 0x00000001000267f8 in rb_eval ()
#291 0x0000000100027afb in rb_eval ()
#292 0x000000010002e530 in rb_call0 ()
#293 0x000000010002f49e in rb_call ()
#294 0x00000001000267f8 in rb_eval ()
#295 0x0000000100025816 in rb_eval ()
#296 0x0000000100027a9c in rb_eval ()
#297 0x000000010002e530 in rb_call0 ()
#298 0x000000010002f49e in rb_call ()
#299 0x00000001000267f8 in rb_eval ()
#300 0x0000000100025816 in rb_eval ()
#301 0x0000000100027a9c in rb_eval ()
#302 0x000000010002e530 in rb_call0 ()
#303 0x000000010002f49e in rb_call ()
#304 0x00000001000267f8 in rb_eval ()
#305 0x000000010002e530 in rb_call0 ()
#306 0x000000010002f49e in rb_call ()
#307 0x00000001000267f8 in rb_eval ()
#308 0x00000001000259ac in rb_eval ()
#309 0x0000000100025c04 in rb_eval ()
#310 0x0000000100024f04 in rb_eval ()
#311 0x000000010002e530 in rb_call0 ()
#312 0x000000010002f49e in rb_call ()
#313 0x0000000100026b2f in rb_eval ()
#314 0x00000001000259ac in rb_eval ()
#315 0x0000000100025c04 in rb_eval ()
#316 0x000000010002b2d4 in rb_yield_0 ()
#317 0x000000010003c480 in rb_thread_yield ()
#318 0x000000010003c113 in rb_thread_start_0 ()
#319 0x000000010003c62e in rb_thread_start ()
#320 0x000000010002e975 in call_cfunc ()
#321 0x000000010002dbb8 in rb_call0 ()
#322 0x000000010002f49e in rb_call ()
#323 0x00000001000267f8 in rb_eval ()
#324 0x000000010002546c in rb_eval ()
#325 0x000000010002e530 in rb_call0 ()
#326 0x000000010002f49e in rb_call ()
#327 0x0000000100026b2f in rb_eval ()
#328 0x0000000100035ebc in block_pass ()
#329 0x00000001000251c8 in rb_eval ()
#330 0x0000000100027b84 in rb_eval ()
#331 0x000000010002b2d4 in rb_yield_0 ()
#332 0x000000010002b70b in rb_yield ()
#333 0x0000000100006b28 in rb_ary_each ()
#334 0x000000010002e9ac in call_cfunc ()
#335 0x000000010002dbb8 in rb_call0 ()
#336 0x000000010002f49e in rb_call ()
#337 0x00000001000267f8 in rb_eval ()
#338 0x000000010002546c in rb_eval ()
#339 0x00000001000259ac in rb_eval ()
#340 0x0000000100024f04 in rb_eval ()
#341 0x000000010002b2d4 in rb_yield_0 ()
#342 0x00000001000258e8 in rb_eval ()
#343 0x000000010002e530 in rb_call0 ()
#344 0x000000010002f49e in rb_call ()
#345 0x00000001000267f8 in rb_eval ()
#346 0x000000010002546c in rb_eval ()
#347 0x000000010002e530 in rb_call0 ()
#348 0x000000010002f49e in rb_call ()
#349 0x00000001000267f8 in rb_eval ()
#350 0x000000010002e530 in rb_call0 ()
#351 0x000000010002f49e in rb_call ()
#352 0x00000001000267f8 in rb_eval ()
#353 0x000000010002e530 in rb_call0 ()
#354 0x000000010002f49e in rb_call ()
#355 0x000000010002fc77 in rb_call_super ()
#356 0x0000000100026fd2 in rb_eval ()
#357 0x0000000100025c04 in rb_eval ()
#358 0x000000010002e530 in rb_call0 ()
#359 0x000000010002f49e in rb_call ()
#360 0x00000001000267f8 in rb_eval ()
#361 0x000000010002b2d4 in rb_yield_0 ()
#362 0x000000010002b70b in rb_yield ()
#363 0x0000000100062706 in rb_obj_tap ()
#364 0x000000010002e9ac in call_cfunc ()
#365 0x000000010002dbb8 in rb_call0 ()
#366 0x000000010002f49e in rb_call ()
#367 0x00000001000267f8 in rb_eval ()
#368 0x000000010002546c in rb_eval ()
#369 0x0000000100020d21 in eval_node ()
#370 0x0000000100031840 in rb_load ()
#371 0x00000001000327a7 in rb_require_safe ()
#372 0x0000000100032204 in rb_f_require ()
#373 0x000000010002e9cb in call_cfunc ()
#374 0x000000010002dbb8 in rb_call0 ()
#375 0x000000010002f49e in rb_call ()
#376 0x0000000100026b2f in rb_eval ()
#377 0x0000000100020d21 in eval_node ()
#378 0x000000010002145e in ruby_exec_internal ()
#379 0x00000001000214ae in ruby_exec ()
#380 0x00000001000214d4 in ruby_run ()
#381 0x0000000100000ec6 in main ()
```

**Comment by evan** [comment] 2011-12-13 10:37
Ah. I was hoping it was in the interface level, but it's not...it's in Aspell itself. Can you upgrade Aspell?

**Comment by huerlisi** [comment] 2011-12-13 11:58
Thanks for looking into this!

Currently using stable 0.60.6, will give the unreleased 0.60.7 a try.

**Comment by huerlisi** [comment] 2011-12-13 12:01
No luck:-(

**Comment by huerlisi** [comment] 2011-12-13 12:03
As I said, thanks for your fast responses and your time! We'll keep investigating, but probably have to work around this problem (doesn't make much sense to get strange suggestions for numbers, anyway:-)

Feel free to close this issue.

**Comment by huerlisi** [comment] 2011-12-13 13:53
Worked around problem on our side...

Found bug reports with similar segfault symptoms for other programs (like http://old.nabble.com/-Bug-233026--New%3A-KMail---Kontact-crash-while-composing-email-td28114919.html).

Closing this issue as raspell can't do much about this.

Thanx

(just found out I don't have the permissions to close... @raskhadafi you probably have:-)

**Comment by evan** [comment] 2011-12-13 17:25
Sounds good. If you can ever consistently reproduce, let me know.

**Closed as completed by evan** 2011-12-13 17:25 UTC
